<a href="https://colab.research.google.com/github/james-monahan/Stats_Calc_Workshop/blob/main/Math7_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

#Basic Calculation

-calculate the time it takes for sunlight to reach the Earth each day of the year

In [2]:
def earth_sun_distance():
    # Semi-major axis between earth and sun
    A = 149600000
    # Eccentricity of earth
    E = 0.0167
    l = []
    for i in range(365):
        theta = (2 * math.pi * i) / 365.25
        r = A*(1 - E**2)/ (1 - (E * math.cos(theta)))
        l.append(r)
    
    return l

In [3]:
l = earth_sun_distance()

# Calculating the time taken
S = 299792 #speed of light
t = np.divide(l, S) #time = distance/speed

sunny = np.asarray(list(zip(l, t)))
print("Earth sun distance: \n", sunny[:5])

Earth sun distance: 
 [[1.52098320e+08 5.07346160e+02]
 [1.52097938e+08 5.07344885e+02]
 [1.52096791e+08 5.07341061e+02]
 [1.52094881e+08 5.07334688e+02]
 [1.52092207e+08 5.07325770e+02]]


#Additional Operations

In [4]:
z = np.array([[1, 2],\
              [3, 4]])
print(type(z))

<class 'numpy.ndarray'>


In [5]:
print("matrix z: ")
print(z)
# Transpose matrix
# Method 1
print("new matrix: ")
print(np.transpose(z))
# Method 2
print(z.transpose())
# Method 3
t = z.transpose()
print(t)

matrix z: 
[[1 2]
 [3 4]]
new matrix: 
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [6]:
y = z.ravel()
print(y)

[1 2 3 4]


In [7]:
j = np.linspace(0,10)
j = j.reshape(5,5,2)
j

array([[[ 0.        ,  0.20408163],
        [ 0.40816327,  0.6122449 ],
        [ 0.81632653,  1.02040816],
        [ 1.2244898 ,  1.42857143],
        [ 1.63265306,  1.83673469]],

       [[ 2.04081633,  2.24489796],
        [ 2.44897959,  2.65306122],
        [ 2.85714286,  3.06122449],
        [ 3.26530612,  3.46938776],
        [ 3.67346939,  3.87755102]],

       [[ 4.08163265,  4.28571429],
        [ 4.48979592,  4.69387755],
        [ 4.89795918,  5.10204082],
        [ 5.30612245,  5.51020408],
        [ 5.71428571,  5.91836735]],

       [[ 6.12244898,  6.32653061],
        [ 6.53061224,  6.73469388],
        [ 6.93877551,  7.14285714],
        [ 7.34693878,  7.55102041],
        [ 7.75510204,  7.95918367]],

       [[ 8.16326531,  8.36734694],
        [ 8.57142857,  8.7755102 ],
        [ 8.97959184,  9.18367347],
        [ 9.3877551 ,  9.59183673],
        [ 9.79591837, 10.        ]]])

In [8]:
j.ravel().shape

(50,)

In [9]:
resize = np.resize(z,(3,3))
resize

array([[1, 2, 3],
       [4, 1, 2],
       [3, 4, 1]])

In [10]:
#operations on axes in an array
z = np.array([[1, 5, 9, 4],\
              [8, 3, 7, 6]])
print(z.max(axis = 0))
print(z.max(axis = 1))
print(z.sum(axis = 1))
print(np.concatenate((z[1], z[0]), axis=0))

[8 5 9 6]
[9 8]
[19 24]
[8 3 7 6 1 5 9 4]


In [11]:
z[1]

array([8, 3, 7, 6])

#Matrix Search

In [12]:
matrix = [[7, 10, 15, 18],\
          [25, 29, 35, 47],\
           [56, 78, 85, 104]]

In [13]:
def matrixsearch(matrix, value):
    # Check for edge cases
    if value is None or not matrix:
         return False

    # Initialize the variables
    row = len(matrix)
    col = len(matrix[0])
    start = 0
    end   = row * col - 1

    while start <= end:
        mid = int((start + end) / 2)

        pointer = matrix[int(mid/col)][int(mid%col)]
        print(int(mid/col), int(mid%col))
        if pointer == value:
            return True
        elif pointer < value:
            start = mid + 1
        else:
            end = mid - 1
    return False
sol = matrixsearch(matrix, 78)
print(sol)

1 1
2 0
2 2
2 1
True


#Multiple Matrices

In [14]:
import numpy as np
z = np.array([[1, 2],\
              [3, 4]])
x = np.array([[4, 5],\
              [7, 8]])
print(np.multiply(x,z))
print(np.multiply(z,x))

[[ 4 10]
 [21 32]]
[[ 4 10]
 [21 32]]


In [15]:
# not interpreted as a matrix
z = np.array([[1,2],[3]])
x = np.array([[4,5]])
print(np.multiply(x,z))

[[list([1, 2, 1, 2, 1, 2, 1, 2]) list([3, 3, 3, 3, 3])]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


#Multiple Matrices Operations

In [16]:
from numpy.linalg import inv

In [17]:
def identity():
    print(np.identity(3))

#offset identity using k
def eye(size, k):
    print(np.eye(size, k = k))

In [18]:
eye(4,0)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
#inverse: produces an identity matrix when you multiply it by the original matrix
z = np.array([[1,2],[3,4]])

def inverse(z):
    z_inv = inv(z)
    product = np.dot(z, z_inv)
    print(z_inv)
    print(product)

inverse(z)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [20]:
def and_op():
    m1 = [True, False, False]
    m2 = [True, False, True]
    print(np.logical_and(m1, m2))
and_op()

[ True False False]


In [22]:
#np.outer for crossproduct
def vector():
    horizontal = np.array([[1,3,2]])
    vertical = np.array([[2],\
                         [0],\
                         [1]])
    print("Output for dimension 1 x 1: ")
    print(horizontal.dot(vertical))
    print("Output for dimension 3 x 3: ")
    print(vertical.dot(horizontal))
    print("Output using outer for getting cross product: ")
    print(np.outer(vertical.ravel(), horizontal.ravel()))
    print(np.outer(horizontal.ravel(), vertical.ravel()))

vector()

Output for dimension 1 x 1: 
[[4]]
Output for dimension 3 x 3: 
[[2 6 4]
 [0 0 0]
 [1 3 2]]
Output using outer for getting cross product: 
[[2 6 4]
 [0 0 0]
 [1 3 2]]
[[2 0 1]
 [6 0 3]
 [4 0 2]]


#Solving Linear Equations

In [41]:
#z is coeff, r is sum#
z = np.array([[37, 20, 12],\
              [15, 32, 4],\
              [5,  40, 2]])

r = np.array([[435],[178],[70]])

In [42]:
print(np.linalg.inv(z))

[[-0.06282723  0.28795812 -0.19895288]
 [-0.0065445   0.0091623   0.02094241]
 [ 0.28795812 -0.90314136  0.57853403]]


In [43]:
X = np.linalg.inv(z).dot(r)
print(X)

[[10.  ]
 [ 0.25]
 [ 5.  ]]


In [44]:
y = np.linalg.solve(z,r)
print(y)

[[10.  ]
 [ 0.25]
 [ 5.  ]]
